### ISSUE TITLE
Support for test tags

### ISSUE THREAD

**Issue by rcostanza** [ncruces/go-coverage-report#18]
My project uses build constraints to omit certain test files from compilation:

```go
// go:build tests
```

So to run tests, I have to explicitly include them in the command:

```bash
go test ./... -tags=tests
```

Would be useful to have a parameter in the action so I could provide tags to be forwarded to an optional test command argument `-tags`.

**Comment by ncruces** [comment]
To not repeat myself, see: https://github.com/ncruces/go-coverage-report/issues/17#issuecomment-2526277877

> This project has increasingly steered away from generating coverage for anything but a bog standard simple repo, where the default just works.

TLDR: you can generate `coverage.out` yourself, with however many sophisticated steps, configuration, etc, then use this to generate the badge/report/chart, like so:
```yaml
- name: Update coverage report
  uses: ncruces/go-coverage-report@v0
  with:
    coverage-file: coverage.out
```
