### ISSUE TITLE
Action failing with `Cannot open: File exists`

### ISSUE THREAD

**Issue by m-danial-r** [ncruces/go-coverage-report#4]
hi, i've tried this action and did work just fine in my public repo with just simple hello world,
but unfortunately this did not work with my company's private repo, it shows hundreds of error stating that `Error: /usr/bin/tar: ../../../go/pkg/mod .... Cannot open: File exists`
![DeepinScreenshot_select-area_20230803223129](https://github.com/ncruces/go-coverage-report/assets/112993413/0442446b-fb44-4cb8-84bc-e10624ffe1c8)

fyi, this action is run as the last step in the job, and before this step i had run these steps
```yaml
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.7
          cache: false

      - name: Build
        run: go build -v ./...

      - name: Set up Mockery
        run: |
          go install github.com/vektra/mockery/v2@v2.32.0
          mockery

      - name: Test
        run: go test -v ./...

      - name: Update Coverage Report
        uses: ncruces/go-coverage-report@v0
        with:
          report: 'false'
          chart: 'false'
          amend: 'true'
          go-version: '1.20.7'
        continue-on-error: true
```

is it error caused by the caching of `actions/setup-go`, but i already disable it with `cache: false`

thank you.
