### ISSUE TITLE
Accept coverage file from a previous step

### ISSUE THREAD

**Issue by qdm12** [ncruces/go-coverage-report#5]
Right now, for various reasons, I run my tests in a Docker container.
What I would like to do is plug in a `coverage.out` file into your action step, would this be possible?

For example:

```yml
      - name: Build test image
        run: docker build -t test-container .

      - name: Run tests in test container
        run: |
          touch coverage.out
          docker run --rm \
          -v "$(pwd)/coverage.out:/tmp/coverage.out" \
          test-container \
          go test -cover -coverprofile=/tmp/coverage.out ./...

      - name: Update coverage report
        uses: ncruces/go-coverage-report@v0
        with:
          coverage-file: ./coverage.out
```

Outside this particular case, it would allow the user to generate a coverage.out file as he wishes (i.e. with different `-covermode` flags)
